[project]
name = "meta_prompt_extractor"
description = "Custom Node To browse and load images and extract prompts form them"
version = "1.8.0"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/ialhabbal/meta_prompt_extractor"

[tool.comfy]
PublisherId = "ialhabbal"
DisplayName = "meta_prompt_extractor"
Icon = "https://raw.githubusercontent.com/ialhabbal/meta_prompt_extractor/main/media/meta_prompt_extractor.png"
includes = []
